// <auto-generated />
using System;
using IM.Web.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IM.Web.Migrations
{
    [DbContext(typeof(IMDbContext))]
    [Migration("20210130160134_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("IM.Web.Database.Entity.AssetEntity", b =>
                {
                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCash")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConvertible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFixIncome")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFuture")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSwap")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
